### ISSUE TITLE
Thanks for the script

### ISSUE THREAD

**Issue by optio50** [Refhi/Shelly-BLU-to-MQTT#1]
Working good so far.
Any way to get the initial status like we do with the Plus devices? mqqt publish command status_update

In addition do you have a plan for the BLU motion sensors? That would be nice as well.

Thanks

**Comment by Refhi** [comment]
Hey,
didn't figure this script would get attention so fast, glad you found it useful !

for now unfortunately I don't have a BLU motion sensor :-/ If I do one day I'll update it.

For the initial status I'm not sure what you mean, could you detail a bit and give me a few examples ?

**Comment by optio50** [comment]
> Hey, didn't figure this script would get attention so fast, glad you found it useful !
> 
> for now unfortunately I don't have a BLU motion sensor :-/ If I do one day I'll update it.
> 
> For the initial status I'm not sure what you mean, could you detail a bit and give me a few examples ?

After the Plus device starts publishing the Window data if a new subscriber comes along you have to wait for the window sensor to change states to get a message (or wait about 1/2 hour for the update to broadcast). 

On a plus device that supports MQTT you can send a publish command to query its status and its refreshed instantly.
Seeing that the window sensors dont natively  support MQTT this cant be done.

Any idea how to query the window sensor on demand without continuous broadcasting?

**Comment by Refhi** [comment]
The problem is that the BLU devices only send a signal on a changed status unless you activate the beacon mode
So I see two options :    
- either you activate the beacon mode (Easy but battery draining)
- either we add a function to the BLU to MQTT script to store the last BLUdoor status, and send it "on demand" through a MQTT or http command.
What do you think ? MQTT or http command ?
I won't be able to work on that for at least a few weeks, but if you feel like making a pull resquest... 😇

**Comment by optio50** [comment]
I tried set the MQTT retained flag to true and it seems to be working as intended.
Messages are now stored with the last state.
I have heard of issues with retained messages but ill see how it goes. 
```

// MQTT publish function
function mqtt_publish(topic, payload) {
    let message = JSON.stringify(payload);
    MQTT.publish(topic, message, 0, true);
}

```
in addition, here is a change to your script that works with motions sensors.
(I used two separate scripts, I havent tried to see if it works combined)


```
let BTH = {};
BTH[0x00] = { n: "pid", t: uint8 };
BTH[0x01] = { n: "battery", t: uint8, u: "%" };
BTH[0x02] = { n: "temperature", t: int16, f: 0.01, u: "tC" };
BTH[0x03] = { n: "humidity", t: uint16, f: 0.01, u: "%" };
BTH[0x05] = { n: "illuminance", t: uint24, f: 0.01 };
BTH[0x21] = { n: "motion", t: uint8 };
BTH[0x2d] = { n: "window", t: uint8 };
BTH[0x3a] = { n: "button", t: uint8 };
BTH[0x3f] = { n: "rotation", t: int16, f: 0.1 };
```

**Comment by Refhi** [comment]
Nice work !
Schedule too full for now, but I'll study your code for a merge asap

**Comment by Refhi** [comment]
implémenté via https://github.com/Refhi/Shelly-BLU-to-MQTT/commit/b04b079dc1db4399026b9519e33dfd1551451663
