### ISSUE TITLE
The scripts stops unexpectedly

### ISSUE THREAD

**Issue by gfplab-scaffardi** [Refhi/Shelly-BLU-to-MQTT#2]
I tried the script and, like other scripts i found for Shelly GEN2 devices, it seems that sometimes randomly stops running. Even if set to "auto start". Have you ever experienced that?

**Comment by Refhi** [comment]
I've read about online but never experienced it myself.
As far as I'm concerned it's still running after 10+ days. 
I'd suggest making a very small script which record in your central and/or locally (via http ? Mqtt ?) time data, and Debug data every second or so on a few GEN2 devices.
With that in hand maybe contact Shelly or Debug ?
Or, dirty solution, use it to monitor the script and reboot the shelly every time it crashes.
(I'm guessing you already tried updating, hard reset and letting only one script online at the same time)

**Comment by Refhi** [comment]
there's been an update with https://github.com/Refhi/Shelly-BLU-to-MQTT/pull/4
did you try it ?
